blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://github.com/mauropriori/ariston_net/discussions
    about: Use discussions for help and general questions.
